#define TMC2_VERSION_MAJOR 15
#define TMC2_VERSION_MINOR 0

/* Define to 1 if getrusage(2) is present */
#define HAVE_GETRUSAGE 1

/* #undef ENABLE_PAPI_PROFILING */

#define USE_JMAPP_VIDEO_CODEC
#define USE_HMAPP_VIDEO_CODEC
#define USE_SHMAPP_VIDEO_CODEC
#define USE_HMLIB_VIDEO_CODEC
#define USE_JMLIB_VIDEO_CODEC
#define USE_VTMLIB_VIDEO_CODEC
/* #undef USE_FFMPEG_VIDEO_CODEC */

#define USE_HDRTOOLS



